### PR TITLE
Migrate away from gulp-util

### PR DESCRIPTION
**Pull request by Kagami**
Hi!

I've removed deprecated gulp-util dependency as per:
- https://github.com/gulpjs/gulp-util
- https://github.com/gulpjs/gulp-util/issues/143
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

I've also made it possible to disable "Optimizing …" message if non-info logLevel is requested.

### CODE REVIEW

**Comment by jlouns** [comment]
Thanks @Kagami!

**Comment by Kagami** [comment]
Could you please publish to npm?

**Comment by jlouns** [comment]
Just updating some dependencies and then I'll publish

**Comment by Kagami** [comment]
Thanks!

**Pull request merged**
